### ISSUE TITLE
Logger host build issue - zeek 

### ISSUE THREAD

**Issue by 2xyo** [cyberdefenders/DetectionLabELK#1]
* Operating System Version: Debian GNU/Linux 10 (buster) 
* Provider (VirtualBox/VMWare): Virtualbox 6.1.4 r136177
* Vagrant Version: 2.2.7
* Packer Version: 1.5.4
* Are you using stock boxes (downloaded) or were they built from scratch using Packer? : from scratch  `./build.sh virtualbox`
* Is the issue reproducible or intermittent? reproducible
### Description of the issue:

While building the logger host, I'm running into the following error message that causes the build to stop:
```console
$ build.sh virtualbox
...
$ tail -n 400  Vagrant/vagrant_up_logger.log 
    logger: [15:00:50]: Installing Zeek...
...
    logger: Requirement already satisfied: smmap>=3.0.1 in /usr/local/lib/python2.7/dist-packages (from smmap2>=2.0.0->gitdb2<3,>=2->gitpython->zkg)
    logger: Traceback (most recent call last):
    logger:   File "/usr/local/bin/zkg", line 2243, in <module>
    logger:     
    logger: main()
    logger:   File "/usr/local/bin/zkg", line 2237, in main
    logger:     
    logger: manager = create_manager(args, config)
    logger:   File "/usr/local/bin/zkg", line 334, in create_manager
    logger:     
    logger: error = manager.add_source(name=key, git_url=value)
    logger:   File "/usr/local/lib/python2.7/dist-packages/zeekpkg/manager.py", line 402, in add_source
    logger:     
    logger: parse_result = urllib.parse.urlparse(git_url)
    logger: AttributeError
    logger: : 
    logger: 'module' object has no attribute 'parse'
    logger: Traceback (most recent call last):
    logger:   File "/usr/local/bin/zkg", line 2243, in <module>
    logger:     
    logger: main()
    logger:   File "/usr/local/bin/zkg", line 2237, in main
    logger:     
    logger: manager = create_manager(args, config)
    logger:   File "/usr/local/bin/zkg", line 334, in create_manager
    logger:     
    logger: error = manager.add_source(name=key, git_url=value)
    logger:   File "/usr/local/lib/python2.7/dist-packages/zeekpkg/manager.py", line 402, in add_source
    logger:     
    logger: parse_result = urllib.parse.urlparse(git_url)
    logger: AttributeError
    logger: : 
    logger: 'module' object has no attribute 'parse'
    logger: Traceback (most recent call last):
    logger:   File "/usr/local/bin/zkg", line 2243, in <module>
    logger:     
    logger: main()
    logger:   File "/usr/local/bin/zkg", line 2237, in main
    logger:     
    logger: manager = create_manager(args, config)
    logger:   File "/usr/local/bin/zkg", line 334, in create_manager
    logger:     
    logger: error = manager.add_source(name=key, git_url=value)
    logger:   File "/usr/local/lib/python2.7/dist-packages/zeekpkg/manager.py", line 402, in add_source
    logger:     
    logger: parse_result = urllib.parse.urlparse(git_url)
    logger: AttributeError
    logger: : 
    logger: 'module' object has no attribute 'parse'
    logger: Job for zeek.service failed because the control process exited with error code.
    logger: See "systemctl status zeek.service" and "journalctl -xe" for details.
    logger: Zeek attempted to start but is not running. Exiting
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

### Link to Gist Containing Build Logs:
https://gist.github.com/2xyo/d826bbaeeb556740320bb2a3677e8b4f

**Comment by lnxg33k** [comment]
Thanks @2xyo that should be fixed, also opened an issue in https://github.com/zeek/package-manager/issues/60
